#!/usr/bin/env bash
set -euo pipefail

# ── Felt Like It — Production Setup Wizard ─────────────────────────────────────
# Generates secrets, writes docker/.env, and starts the stack.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOCKER_DIR="$SCRIPT_DIR/docker"
ENV_FILE="$DOCKER_DIR/.env"

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║           Felt Like It — Production Setup                   ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# ── Check prerequisites ────────────────────────────────────────────────────────
for cmd in docker openssl; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "ERROR: $cmd is required but not found."
    exit 1
  fi
done

if ! docker compose version &>/dev/null; then
  echo "ERROR: docker compose plugin is required."
  exit 1
fi

# ── Guard against overwriting ──────────────────────────────────────────────────
if [ -f "$ENV_FILE" ]; then
  echo "docker/.env already exists."
  read -rp "Overwrite? [y/N] " overwrite
  if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
    echo "Aborted."
    exit 0
  fi
fi

# ── Collect inputs ─────────────────────────────────────────────────────────────
read -rp "Domain (e.g., maps.example.com) [localhost]: " DOMAIN
DOMAIN="${DOMAIN:-localhost}"

if [ "$DOMAIN" = "localhost" ]; then
  ORIGIN="http://localhost:3000"
  USE_TRAEFIK=false
  echo ""
  echo "  → localhost mode: no TLS, direct port 3000"
else
  ORIGIN="https://$DOMAIN"
  USE_TRAEFIK=true

  read -rp "Email for Let's Encrypt certificates: " ACME_EMAIL
  if [ -z "$ACME_EMAIL" ]; then
    echo "ERROR: ACME_EMAIL is required for TLS."
    exit 1
  fi
  echo ""
  echo "  → Production mode: Traefik + Let's Encrypt TLS"
fi

# ── Generate secrets ───────────────────────────────────────────────────────────
POSTGRES_PASSWORD="$(openssl rand -hex 32)"
SESSION_SECRET="$(openssl rand -hex 32)"
REDIS_PASSWORD="$(openssl rand -hex 32)"

echo ""
echo "Secrets generated."

# ── Write .env ─────────────────────────────────────────────────────────────────
cat > "$ENV_FILE" <<EOF
# Generated by setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# See docker/.env.example for documentation.

DOMAIN=$DOMAIN
ACME_EMAIL=${ACME_EMAIL:-}
ORIGIN=$ORIGIN

POSTGRES_USER=felt
POSTGRES_DB=felt
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

SESSION_SECRET=$SESSION_SECRET
LOG_LEVEL=info

REDIS_PASSWORD=$REDIS_PASSWORD
EOF

echo "Wrote docker/.env"

# ── Start the stack ────────────────────────────────────────────────────────────
echo ""
echo "Starting containers..."

cd "$DOCKER_DIR"

if [ "$USE_TRAEFIK" = true ]; then
  docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build
else
  docker compose up -d --build
fi

# ── Wait for health ────────────────────────────────────────────────────────────
echo ""
echo "Waiting for services to be healthy..."

MAX_WAIT=120
ELAPSED=0
while [ $ELAPSED -lt $MAX_WAIT ]; do
  if [ "$USE_TRAEFIK" = true ]; then
    HEALTH=$(docker compose -f docker-compose.yml -f docker-compose.prod.yml ps --format json 2>/dev/null | grep -c '"healthy"' || true)
  else
    HEALTH=$(docker compose ps --format json 2>/dev/null | grep -c '"healthy"' || true)
  fi

  if [ "$HEALTH" -ge 3 ] 2>/dev/null; then
    break
  fi

  sleep 5
  ELAPSED=$((ELAPSED + 5))
  echo "  ... ${ELAPSED}s (${HEALTH:-0} healthy)"
done

echo ""
echo "══════════════════════════════════════════════════════════════"
echo ""
echo "  Felt Like It is running!"
echo ""
echo "  URL:     $ORIGIN"
echo "  Login:   demo@felt-like-it.local / demo"
echo "           (after running: pnpm seed)"
echo ""
echo "  Backup:  ./docker/backup.sh"
echo "  Restore: ./docker/restore.sh <timestamp>"
echo ""
echo "══════════════════════════════════════════════════════════════"
